### ISSUE TITLE
Timeout when getting workflow status

### ISSUE THREAD

**Issue by hkeward** [aws/amazon-genomics-cli#229] opened 2021-12-15 19:20 UTC
[//]: #  (Please do not include your AWS account or credentials as part of the bug request.)

**Describe the Bug**

[//]: #  (Please describe the behavior that you are seeing with as many details as possible including logs from AGC, CloudWatch snippets and CloudFormation errors if relevant.)

When running `agc workflow status`, I am unable to get a list of workflows/statuses due to repeated timeouts. I am also unable to submit new workflows.

**Steps to Reproduce**

[//]: #  (Include a list of steps that can be used to reproduce the bug.)

This started happening on December 1, 2021 after successfully submitting ~7500 workflows via `agc` (using WDL and Cromwell) between November 24 and December 1. Since then, I have not been able to retrieve workflow statuses or submit new workflows via `agc`.

These are the counts and statuses of my workflows as of December 1:
```
   6734 COMPLETE
    444 EXECUTOR_ERROR
     77 RUNNING
    327 INITIALIZING
```

**Relevant Logs**

[//]: #  (The logs that where obtained by running the commands here. Please run the command with "-v" so that we can see the verbose logs.)
Output of `agc workflow status -v`:
```
2021-12-15T14:10:27-05:00 ↓  Checking AGC version...
2021-12-15T14:10:27-05:00 𝒊  Showing workflow run(s). Max Runs: 20
2021-12-15T14:10:28-05:00 ↓  EstablishWesConnection(https://is4k954kk8.execute-api.us-west-2.amazonaws.com/prod/ga4gh/wes/v1)
2021-12-15T14:10:28-05:00 ↓  Ping WES endpoint until we get an answer:
2021-12-15T14:10:28-05:00 ↓  Attempt 1 of 3
2021-12-15T14:10:57-05:00 ⚠️  Call to WES endpoint 'https://is4k954kk8.execute-api.us-west-2.amazonaws.com/prod/ga4gh/wes/v1' failed: 504 Gateway Timeout
2021-12-15T14:11:00-05:00 ↓  Attempt 2 of 3
2021-12-15T14:11:29-05:00 ⚠️  Call to WES endpoint 'https://is4k954kk8.execute-api.us-west-2.amazonaws.com/prod/ga4gh/wes/v1' failed: 504 Gateway Timeout
2021-12-15T14:11:32-05:00 ↓  Attempt 3 of 3
2021-12-15T14:12:01-05:00 ⚠️  Call to WES endpoint 'https://is4k954kk8.execute-api.us-west-2.amazonaws.com/prod/ga4gh/wes/v1' failed: 504 Gateway Timeout
2021-12-15T14:12:04-05:00 ✘   error="attempts to establish a connection to WES service endpoint https://is4k954kk8.execute-api.us-west-2.amazonaws.com/prod/ga4gh/wes/v1 timed out"
Error: an error occurred invoking 'workflow status'
with variables: {MaxInstances:20 InstanceId: WorkflowName: ContextName:}
caused by: attempts to establish a connection to WES service endpoint https://is4k954kk8.execute-api.us-west-2.amazonaws.com/prod/ga4gh/wes/v1 timed out
```

I'm still able to connect to the engine, here is the tail of `agc logs engine --context default` (this particular error is repeated many times):
```
Wed, 15 Dec 2021 13:50:03 -0500	2021-12-15 18:50:03,844  INFO  - Running with database db.url = 
Wed, 15 Dec 2021 13:50:03 -0500	    jdbc:hsqldb:file:cromwell-executions/cromwell-db/cromwell-db;
Wed, 15 Dec 2021 13:50:03 -0500	    shutdown=false;
Wed, 15 Dec 2021 13:50:03 -0500	    hsqldb.default_table_type=cached;hsqldb.tx=mvcc;
Wed, 15 Dec 2021 13:50:03 -0500	    hsqldb.result_max_memory_rows=10000;
Wed, 15 Dec 2021 13:50:03 -0500	    hsqldb.large_data=true;
Wed, 15 Dec 2021 13:50:03 -0500	    hsqldb.applog=1;
Wed, 15 Dec 2021 13:50:03 -0500	    hsqldb.lob_compressed=true;
Wed, 15 Dec 2021 13:50:03 -0500	    hsqldb.script_format=3
Wed, 15 Dec 2021 13:50:03 -0500	    
Wed, 15 Dec 2021 13:50:04 -0500	2021-12-15 18:50:04,367  INFO  - dataFileCache open start
Wed, 15 Dec 2021 13:50:04 -0500	2021-12-15 18:50:04,372  INFO  - data file was not modified but inc backup exists
Wed, 15 Dec 2021 13:50:04 -0500	2021-12-15 18:50:04,388  INFO  - dataFileCache open end
Wed, 15 Dec 2021 13:51:57 -0500	2021-12-15 18:51:57,672  INFO  - checkpointClose start
Wed, 15 Dec 2021 13:51:57 -0500	2021-12-15 18:51:57,672  INFO  - checkpointClose synched
Wed, 15 Dec 2021 13:52:04 -0500	2021-12-15 18:52:04,140  ERROR - Failed to instantiate Cromwell System. Shutting down Cromwell.
Wed, 15 Dec 2021 13:52:04 -0500	java.sql.SQLTransientConnectionException: db - Connection is not available, request timed out after 120005ms.
Wed, 15 Dec 2021 13:52:04 -0500		at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
Wed, 15 Dec 2021 13:52:04 -0500		at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
Wed, 15 Dec 2021 13:52:04 -0500		at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
Wed, 15 Dec 2021 13:52:04 -0500		at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
Wed, 15 Dec 2021 13:52:04 -0500		at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
Wed, 15 Dec 2021 13:52:04 -0500		at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
Wed, 15 Dec 2021 13:52:04 -0500		at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
Wed, 15 Dec 2021 13:52:04 -0500		at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
Wed, 15 Dec 2021 13:52:04 -0500		at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:250)
Wed, 15 Dec 2021 13:52:04 -0500		at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:249)
Wed, 15 Dec 2021 13:52:04 -0500		at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
Wed, 15 Dec 2021 13:52:04 -0500		at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:275)
Wed, 15 Dec 2021 13:52:04 -0500		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Wed, 15 Dec 2021 13:52:04 -0500		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Wed, 15 Dec 2021 13:52:04 -0500		at java.base/java.lang.Thread.run(Thread.java:829)
Wed, 15 Dec 2021 13:52:08 -0500	2021-12-15 18:52:08,366  INFO  - checkpointClose script done
Wed, 15 Dec 2021 13:52:08 -0500	2021-12-15 18:52:08,367  INFO  - dataFileCache commit start
qwWed, 15 Dec 2021 14:15:16 -0500	2021-12-15 19:15:16,940  ERROR - Failed to instantiate Cromwell System. Shutting down Cromwell.
Wed, 15 Dec 2021 14:15:16 -0500	java.sql.SQLTransientConnectionException: db - Connection is not available, request timed out after 120002ms.
Wed, 15 Dec 2021 14:15:16 -0500		at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
Wed, 15 Dec 2021 14:15:16 -0500		at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
Wed, 15 Dec 2021 14:15:16 -0500		at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
Wed, 15 Dec 2021 14:15:16 -0500		at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
Wed, 15 Dec 2021 14:15:16 -0500		at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
Wed, 15 Dec 2021 14:15:16 -0500		at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
Wed, 15 Dec 2021 14:15:16 -0500		at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
Wed, 15 Dec 2021 14:15:16 -0500		at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
Wed, 15 Dec 2021 14:15:16 -0500		at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:250)
Wed, 15 Dec 2021 14:15:16 -0500		at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:249)
Wed, 15 Dec 2021 14:15:16 -0500		at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
Wed, 15 Dec 2021 14:15:16 -0500		at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:275)
Wed, 15 Dec 2021 14:15:16 -0500		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Wed, 15 Dec 2021 14:15:16 -0500		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Wed, 15 Dec 2021 14:15:16 -0500		at java.base/java.lang.Thread.run(Thread.java:829)
```

**Expected Behavior**

[//]: #  (A clear and concise description of what you expected to happen.)

No timeout.

**Actual Behavior**

[//]: #  (A clear and concise description of what actually happened.)

I am no longer able to use `agc` to submit workflows, get workflow statuses, etc. - I get a timeout every time.

**Additional Context**

[//]: #  (Add any other context about the problem here. The minimum required information is below)

Operating System: Debian GNU/Linux 10 (buster)
AGC Version: 1.1.2
Was AGC setup with a custom bucket: No
Was AGC setup with a custom VPC: Yes

**Comment by tneely** [comment] 2021-12-15 20:35
Hi  hkeward, these error coincide roughly with 1.1.2 release. Were you ever able to get the 1.1.2 version working here? Also, which version did you upgrade from?

There's a chance some of the underlying configuration Cromwell uses has changed since the release, causing this issue. Could you try reactivating your account (`agc account activate --vpc <your-vpc-id>`) and redploying the context (`agc context deploy <your-context-name>`) to ensure that AGC is using the latest Cromwell image and AWS infrastructure?

**Comment by markjschreiber** [comment] 2021-12-15 20:57
This error indicates that Cromwell is not able to connect to it's metadata DB:
```
Wed, 15 Dec 2021 14:15:16 -0500	2021-12-15 19:15:16,940  ERROR - Failed to instantiate Cromwell System. Shutting down Cromwell.
Wed, 15 Dec 2021 14:15:16 -0500	java.sql.SQLTransientConnectionException: db - Connection is not available, request timed out after 120002ms.
```

Not sure if that is causal or a by product of a larger problem? Either way if the engine doesn't start no work will be performed or submitted.

The DB is file based and located at `jdbc:hsqldb:file:cromwell-executions/cromwell-db/cromwell-db`. It's possible this is no longer reachable or perhaps the disk is full?

A context redeploy might help remedy both of these issues although doesn't pin point the cause.

**Comment by hkeward** [comment] 2021-12-15 21:02
Thanks @tneely - I'm not sure what version I was working with before 1.1.2 - probably 1.0.1, based on when I installed it ~mid October. I believe I upgraded to 1.1.2 on November 30th, though unfortunately I can't recall if I did manage to run any workflows using that version or not.

I ran both of the steps you suggested successfully, but I am still getting the timeout error.

**Comment by waliag87** [comment] 2022-01-11 19:40
Closing as we discussed with the user offline and problem has been resolved.

**Closed by waliag87** 2022-01-11 19:40 UTC
Labels: bug
